Odiseo\SyliusBrevoPlugin\Entity\ChannelConfiguration:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [channel]
            message: 'odiseo_brevo.channel_configuration.channel.unique'
            groups: ['odiseo_brevo']
        - Odiseo\SyliusBrevoPlugin\Validator\Constraints\RequiredModules:
            groups: ['odiseo_brevo']
    properties:
        channel:
            - NotBlank:
                message: 'odiseo_brevo.channel_configuration.channel.not_blank'
                groups: ['odiseo_brevo']
        senderName:
            - Length:
                max: 255
                groups: ['odiseo_brevo']
        senderEmail:
            - Email:
                message: 'odiseo_brevo.channel_configuration.sender_email.invalid'
                groups: ['odiseo_brevo']
            - Length:
                max: 255
                groups: ['odiseo_brevo']
        trackerClientKey:
            - Length:
                max: 64
                groups: ['odiseo_brevo']
            - Regex:
                pattern: '/^[A-Za-z0-9]+$/'
                message: 'odiseo_brevo.channel_configuration.tracker_client_key.invalid'
                groups: ['odiseo_brevo']
